age1 = int(input("Enter the age of the first person: "))
age2 = int(input("Enter the age of the second person: "))
age3 = int(input("Enter the age of the third person: "))
oldest = max(age1, age2, age3)
youngest = min(age1, age2, age3)
print(f"The oldest person is {oldest} years old.")
print(f"The youngest person is {youngest} years old.")
